---
- name: Install Tomcat 8
  apt: name={{ item }} state=present
  with_items:
    - tomcat8
    - tomcat8-admin
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

#- name: Enable Tomcat 8 remote debugging
#  template: src=tomcat8.j2 dest=/etc/default/tomcat8

- name: Configure Tomcat 8 Users
  template: src=tomcat-users.xml.j2 dest=/var/lib/tomcat8/conf/tomcat-users.xml
#  notify: tomcat8-restart

#- name: Configure for Tomcat 8 logs
#  template: src=logging.properties.j2 dest=/var/lib/tomcat8/conf/logging.properties owner=root group=tomcat8
#  notify: tomcat8-restart

#- name: Configure server for caching
#  template: src=server.xml.j2 dest=/etc/tomcat8/server.xml
#  notify: tomcat8-restart
